export type Exercise = {
	id: number;
	name: string;
	muscle: string;
	difficulty: "Beginner" | "Intermediate" | "Advanced";
	description: string;
	estimatedCalories: string;
};

export const EXERCISE_LIBRARY: Exercise[] = [
	{
		id: 1,
		name: "Bench Press",
		muscle: "Chest",
		difficulty: "Intermediate",
		description:
			"Classic barbell press for upper chest, shoulders and triceps.",
		estimatedCalories: "8-12 per set",
	},
	{
		id: 2,
		name: "Squat",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "The king of lower body exercises.",
		estimatedCalories: "12-18 per set",
	},
	{
		id: 3,
		name: "Deadlift",
		muscle: "Back",
		difficulty: "Advanced",
		description: "Full posterior chain movement.",
		estimatedCalories: "15-20 per set",
	},
	{
		id: 4,
		name: "Overhead Press",
		muscle: "Shoulders",
		difficulty: "Intermediate",
		description: "Builds strong shoulders and triceps.",
		estimatedCalories: "7-10 per set",
	},
	{
		id: 5,
		name: "Pull Up",
		muscle: "Back",
		difficulty: "Intermediate",
		description: "Best bodyweight back builder.",
		estimatedCalories: "8-12 per set",
	},
	{
		id: 6,
		name: "Barbell Row",
		muscle: "Back",
		difficulty: "Intermediate",
		description: "Excellent horizontal pulling movement.",
		estimatedCalories: "9-13 per set",
	},
	{
		id: 7,
		name: "Dumbbell Curl",
		muscle: "Arms",
		difficulty: "Beginner",
		description: "Classic biceps isolation.",
		estimatedCalories: "4-6 per set",
	},
	{
		id: 8,
		name: "Tricep Extension",
		muscle: "Arms",
		difficulty: "Beginner",
		description: "Targets all three heads of the triceps.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 9,
		name: "Leg Press",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "Machine-based leg movement.",
		estimatedCalories: "10-15 per set",
	},
	{
		id: 10,
		name: "Lunges",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "Unilateral leg exercise.",
		estimatedCalories: "8-12 per set",
	},
	{
		id: 11,
		name: "Lat Pulldown",
		muscle: "Back",
		difficulty: "Beginner",
		description: "Great vertical pulling movement.",
		estimatedCalories: "7-10 per set",
	},
	{
		id: 12,
		name: "Face Pull",
		muscle: "Shoulders",
		difficulty: "Intermediate",
		description: "Rear delt and upper back exercise.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 13,
		name: "Incline Bench Press",
		muscle: "Chest",
		difficulty: "Intermediate",
		description: "Upper chest focused press.",
		estimatedCalories: "8-11 per set",
	},
	{
		id: 14,
		name: "Romanian Deadlift",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "Hamstring and glute focused.",
		estimatedCalories: "12-16 per set",
	},
	{
		id: 15,
		name: "Push Up",
		muscle: "Chest",
		difficulty: "Beginner",
		description: "Bodyweight chest builder.",
		estimatedCalories: "4-6 per set",
	},
	{
		id: 16,
		name: "Plank",
		muscle: "Core",
		difficulty: "Beginner",
		description: "Core stability exercise.",
		estimatedCalories: "3-5 per set",
	},
	{
		id: 17,
		name: "Chest Fly",
		muscle: "Chest",
		difficulty: "Intermediate",
		description: "Isolation for chest stretch.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 18,
		name: "Lateral Raise",
		muscle: "Shoulders",
		difficulty: "Beginner",
		description: "Side delt isolation.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 19,
		name: "Hammer Curl",
		muscle: "Arms",
		difficulty: "Beginner",
		description: "Biceps and forearm curl.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 20,
		name: "Calf Raise",
		muscle: "Legs",
		difficulty: "Beginner",
		description: "Calf builder.",
		estimatedCalories: "4-6 per set",
	},
	{
		id: 21,
		name: "Bent Over Row",
		muscle: "Back",
		difficulty: "Intermediate",
		description: "Back thickness builder.",
		estimatedCalories: "9-13 per set",
	},
	{
		id: 22,
		name: "Dips",
		muscle: "Chest",
		difficulty: "Intermediate",
		description: "Bodyweight triceps and chest.",
		estimatedCalories: "8-12 per set",
	},
	{
		id: 23,
		name: "Leg Extension",
		muscle: "Legs",
		difficulty: "Beginner",
		description: "Quad isolation.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 24,
		name: "Leg Curl",
		muscle: "Legs",
		difficulty: "Beginner",
		description: "Hamstring isolation.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 25,
		name: "Seated Row",
		muscle: "Back",
		difficulty: "Beginner",
		description: "Horizontal pull machine.",
		estimatedCalories: "7-10 per set",
	},
	{
		id: 26,
		name: "Arnold Press",
		muscle: "Shoulders",
		difficulty: "Intermediate",
		description: "Rotational shoulder press.",
		estimatedCalories: "8-11 per set",
	},
	{
		id: 27,
		name: "Cable Fly",
		muscle: "Chest",
		difficulty: "Intermediate",
		description: "Constant tension chest fly.",
		estimatedCalories: "7-9 per set",
	},
	{
		id: 28,
		name: "Russian Twist",
		muscle: "Core",
		difficulty: "Intermediate",
		description: "Rotational core exercise.",
		estimatedCalories: "5-8 per set",
	},
	{
		id: 29,
		name: "Farmer's Walk",
		muscle: "Full Body",
		difficulty: "Intermediate",
		description: "Full body and grip strength.",
		estimatedCalories: "12-18 per set",
	},
	{
		id: 30,
		name: "Hip Thrust",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "Best glute builder.",
		estimatedCalories: "10-14 per set",
	},
	{
		id: 31,
		name: "Chin Up",
		muscle: "Back",
		difficulty: "Intermediate",
		description: "Supinated pull up.",
		estimatedCalories: "9-13 per set",
	},
	{
		id: 32,
		name: "Skull Crushers",
		muscle: "Arms",
		difficulty: "Intermediate",
		description: "Triceps isolation.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 33,
		name: "Front Raise",
		muscle: "Shoulders",
		difficulty: "Beginner",
		description: "Front delt isolation.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 34,
		name: "Hack Squat",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "Machine squat variation.",
		estimatedCalories: "11-16 per set",
	},
	{
		id: 35,
		name: "Cable Row",
		muscle: "Back",
		difficulty: "Beginner",
		description: "Seated cable row.",
		estimatedCalories: "7-10 per set",
	},
	{
		id: 36,
		name: "Hanging Leg Raise",
		muscle: "Core",
		difficulty: "Intermediate",
		description: "Advanced core exercise.",
		estimatedCalories: "6-9 per set",
	},
	{
		id: 37,
		name: "Preacher Curl",
		muscle: "Arms",
		difficulty: "Beginner",
		description: "Strict biceps curl.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 38,
		name: "Bulgarian Split Squat",
		muscle: "Legs",
		difficulty: "Intermediate",
		description: "Unilateral leg strength.",
		estimatedCalories: "10-14 per set",
	},
	{
		id: 39,
		name: "Dumbbell Shoulder Press",
		muscle: "Shoulders",
		difficulty: "Intermediate",
		description: "Dumbbell overhead press.",
		estimatedCalories: "8-11 per set",
	},
	{
		id: 40,
		name: "Glute Bridge",
		muscle: "Legs",
		difficulty: "Beginner",
		description: "Glute activation.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 41,
		name: "T-Bar Row",
		muscle: "Back",
		difficulty: "Intermediate",
		description: "Landmine row.",
		estimatedCalories: "10-14 per set",
	},
	{
		id: 42,
		name: "Concentration Curl",
		muscle: "Arms",
		difficulty: "Beginner",
		description: "Strict isolation curl.",
		estimatedCalories: "4-6 per set",
	},
	{
		id: 43,
		name: "Chest Supported Row",
		muscle: "Back",
		difficulty: "Intermediate",
		description: "Lower back friendly row.",
		estimatedCalories: "8-12 per set",
	},
	{
		id: 44,
		name: "Side Plank",
		muscle: "Core",
		difficulty: "Intermediate",
		description: "Lateral core stability.",
		estimatedCalories: "4-6 per set",
	},
	{
		id: 45,
		name: "Machine Fly",
		muscle: "Chest",
		difficulty: "Beginner",
		description: "Pec isolation machine.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 46,
		name: "Standing Calf Raise",
		muscle: "Legs",
		difficulty: "Beginner",
		description: "Standing calf raise.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 47,
		name: "Reverse Fly",
		muscle: "Shoulders",
		difficulty: "Intermediate",
		description: "Rear delt isolation.",
		estimatedCalories: "6-8 per set",
	},
	{
		id: 48,
		name: "Zercher Squat",
		muscle: "Legs",
		difficulty: "Advanced",
		description: "Advanced squat variation.",
		estimatedCalories: "14-18 per set",
	},
	{
		id: 49,
		name: "Cable Tricep Pushdown",
		muscle: "Arms",
		difficulty: "Beginner",
		description: "Triceps pushdown.",
		estimatedCalories: "5-7 per set",
	},
	{
		id: 50,
		name: "Ab Wheel Rollout",
		muscle: "Core",
		difficulty: "Advanced",
		description: "Advanced core stability.",
		estimatedCalories: "8-12 per set",
	},
];

export default EXERCISE_LIBRARY;
